version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile  # Explicitly specify Dockerfile
    ports:
      - "8081:8080"  # Change host port if 8080 is occupied
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile  # Explicitly specify Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    restart: unless-stopped
