version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Ensure ./backend/Dockerfile exists
    ports:
      - "8081:8080"  # Maps host 8081 to container 8080
    env_file:
      - ./backend/.env  # Ensure this file exists
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Ensure ./frontend/Dockerfile exists
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker  # Ensure this file exists
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
