version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"  # Change to a different host port like 8081
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    restart: unless-stopped
